### ISSUE TITLE
[Question] Is there any method to set variables outside GUI?

### ISSUE THREAD

**Issue by orsson9** [mole3421278/Daibotuten-futures-trading-optimizer-bot#7] opened 2022-03-28 11:40 UTC
For example GUI is allowing user to set "Amount per positon" from range 2 - 20 USDT.
Is there any method to go beyond this limitation like for example changing config file?

Possible enhancement -> have some kind of tick box in GUI called pro mode -> if selected user have wider range for selecting properties like amout per position, leverage etc.

**Comment by mole3421278** [comment] 2022-03-28 12:24
It's implementable. You have a point: for the moment the settings are set to moderate the risk, that is to keep impossible to use a high leverage that can cause to lose everything in a fluctuation caused by market manipulation and to keep low the exposure to a single position limiting the maximum amount per position (if someone has only 100 usdt and put everything in a single position, then it's plausible that it will lose everything really soon). 
However for expert people these limitations can be lifted as you suggest.
Which kind of settings can be useful to be changed in a config file?

**Comment by mole3421278** [comment] 2022-03-28 12:25
List all of them, I'll give a thought about them and implement a new version

**Comment by orsson9** [comment] 2022-03-28 13:42
Thanks for consideration.

Properties to be more adjustable:
- Leverage
- Amount per position
- Stop Loss 
- Take profit

We can put into consideration all Buy / Dont buy properties.

**Comment by mole3421278** [comment] 2022-03-28 20:53
Yes, if cryptos for buy/don't buy are listed in a config file then it results as less boring to set it up the bot whenever it restarts.
Will add this upgrade, thank you for the proposal.

**Comment by mole3421278** [comment] 2022-03-31 21:39
Released the upgrade proposed by orsson9.
Thank you very much for the proposal.
Closing this issue.

**Closed by mole3421278** 2022-03-31 21:39 UTC
