### ISSUE TITLE
Bot not activated

### ISSUE THREAD

**Issue by orsson9** [mole3421278/Daibotuten-futures-trading-optimizer-bot#5] opened 2022-03-15 17:53 UTC
I have paid the full price (15.5 FTM about 1.07 $ per 1 FTM) however the bot didnt activate for 4 hours. Please contact me.

**Comment by mole3421278** [comment] 2022-03-15 18:05
Hello, 
just to be sure, are you in a state where the trading of futures has been banned? If you don't know, try to open manually a futures position on Binance and check if you are allowed to open it or not.
Meanwhile we'll check if there is some other problems.

**Comment by mole3421278** [comment] 2022-03-15 18:39
Right now the bot doesn't have problems, so the suggestions are to:
- check if in your state the trading of futures has been banned;
- check if you linked the bot to a valid API key (check in the section "API management" of binance if you gave to the API the permissions it needs).

If the problem sussists try to download and start the twin bot Benzaiboten (if you paid for Daibotuten you have granted the usage also of Benzaiboten, but it is for the spot trading, so if the problem is that your state has the ban on the futures you should be fine with it, but remember to give to Benzaiboten an API key with permissions to operate in the spot zone).

Also, you can share here the transaction of the payment to check if there are problems there.

**Comment by orsson9** [comment] 2022-03-19 08:55
Kindly reminder.

czw., 17 mar 2022 o 09:30 Adam Lazar ***@***.***> napisał(a):

**Comment by mole3421278** [comment] 2022-03-19 10:05
Hi, thank you for your efforts to find the problem.
I'd say the problem is here: "Don't know if it has any value but bot is printing always the same
 timestamp on console -> 2022.03.15 15:23:26"

The correct behaviour is the following one:
![screen](https://user-images.githubusercontent.com/91144525/159115615-3770f5e4-8ae7-4877-8441-ce4bbf7d7cec.png)

You should see the timestamp changing with the time, so the problem should be in the clock or something related to that.

Try writing this API of binance in the browser multiple times: https://api.binance.com/api/v3/time
The correct behaviour that you should see everytime you execute it is a different number, like:
{"serverTime":1647684112817}
{"serverTime":1647684286951}
{"serverTime":1647684301099}
and so on.
Tell me if you see always the same result.

**Comment by mole3421278** [comment] 2022-03-19 11:37
Also, try the following (taken from Stackoverflow):
If you are running Windows 10, or Windows 11, do the following:

- Start -> search date and time
- Make sure you have set Set time automatically to On
- In the opened window you have an option Synchronize your clock, and press Sync now.

**Comment by mole3421278** [comment] 2022-03-19 11:51
Another thing to check:
you paid the fees using FTM from binance or from another exchange or external wallet?

**Comment by orsson9** [comment] 2022-03-19 12:17
Hello

For some reason the bot is always printing the same time and date, even
after clock sync and system reboot.
But when I enter https://api.binance.com/api/v3/time I get a different
result every time.

FTM was sent from Binance spot wallet.

Best Regards


[image: timeandDate.png]

sob., 19 mar 2022 o 12:52 mole ***@***.***> napisał(a):

**Comment by mole3421278** [comment] 2022-03-19 13:07
Can you share a screenshot of the log of the bot?

**Comment by mole3421278** [comment] 2022-03-19 18:56
Show also a screenshot of the window of the bot, thank you

**Comment by orsson9** [comment] 2022-03-19 20:18
Attaching requested screen. Twitter errors are sometimes visible.

[image: screen.jpg]


sob., 19 mar 2022 o 19:56 mole ***@***.***> napisał(a):

**Comment by mole3421278** [comment] 2022-03-19 20:21
I'm sorry, can't see the image, but only this: "[image: screen.jpg]"
Please, load the image on the discussion of GitHub

**Comment by orsson9** [comment] 2022-03-19 20:25
![screen](https://user-images.githubusercontent.com/47485063/159137320-b468f268-541f-4429-9a31-b8c8cd58562e.jpg)

**Comment by mole3421278** [comment] 2022-03-19 20:36
Thank you. 
The error regarding twitter is known and due to the connectivity with twitter, that sometimes goes down, nothing scary, it returns to work automatically after a while.
Regarding the fees, the suspect is that the transaction has registered a lower value in USDT, so it doesn't count to activate the bot. 
Write down an address (on the Fantom Network, it's okay the same from which you tried to send the fee) to give you back your FTM and try again with another transaction (you can also change the crypto to use if you want). Thank you

**Comment by orsson9** [comment] 2022-03-20 10:49
Thank you.

Coin and network FTM:

0xeb9d2bfa8c26dd0ab5edb86de6073f7099a83087

**Comment by mole3421278** [comment] 2022-03-20 10:54
Done
https://ftmscan.com/tx/0xa895f9ad2e12380a1b8e74e9ded7d518da19e4374e71ee99b03e7afada49d82a

**Comment by mole3421278** [comment] 2022-03-20 13:43
Is the bot active now?

**Comment by mole3421278** [comment] 2022-03-21 14:46
To investigate the problem I'm going to release a new version with more information on the log.

**Comment by mole3421278** [comment] 2022-03-21 15:06
Try this new version: https://github.com/mole3421278/Daibotuten-futures-trading-optimizer-bot/releases/tag/v1.5.1
It won't solve the problem, but it can give me useful information to solve the problem.
Post here the screenshot of the log generated with this new version.
Thank you

**Comment by orsson9** [comment] 2022-03-21 16:46
Didn't spot the new log messages.

**Comment by mole3421278** [comment] 2022-03-21 16:56
Okay, so the problem must be in the clock. Go to Binance and tell me the time at which the last transaction happened according to Binance. Thank you.

**Comment by mole3421278** [comment] 2022-03-21 19:49
Try this new version: https://github.com/mole3421278/Daibotuten-futures-trading-optimizer-bot/releases/tag/v1.5.2
Now the problem should be solved. Let me know, thank you.

**Comment by orsson9** [comment] 2022-03-21 22:44
This version is up to date
PAID: 18.136647999999997 usdt on 2022-03-20 11:07:04
CHECK: FEE PAID CORRECTLY
2022-03-20 11:27:04
PAID: 18.136647999999997 usdt on 2022-03-20 11:07:04
CHECK: FEE PAID CORRECTLY
CHECK: FEES PAID
Started to work to trade!


Thank you for all your support.

**Comment by mole3421278** [comment] 2022-03-21 22:52
Nice! Closing this issue.
if you have any other problem or suggestion do not hesitate to propose it.
Good trading.

**Closed by mole3421278** 2022-03-21 22:52 UTC
